- name: Create minecraft user account
  user:
    name: "{{ minecraft_user }}"

- name: Copy minecraft scripts and config files
  copy: 
    src: "files/srv/"
    dest: /srv/minecraft/
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Create minecraft backups directory
  file:
    path: /srv/minecraft/backups/
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Add minecraft script x permissions
  file:
    path: /srv/minecraft/{{ item }}
    mode: a+x
  loop:
    - start.sh
    - stop.sh
    - backup.sh

# ----- ----- ----- ----- -----

- name: Set SELinux permissions on minecraft scripts
  when: ansible_distribution == 'Fedora'
  sefcontext:
    target: "/srv/minecraft/{{ item }}"
    setype: bin_t
  loop:
    - start.sh
    - stop.sh
    - backup.sh

- name: reload SELinux policy for minecraft scripts
  when: ansible_distribution == 'Fedora'
  command: restorecon -irv /srv/minecraft/

# ----- ----- ----- ----- -----

- name: Write minecraft variables to files
  no_log: true
  copy:
    content: "{{ item.content }}"
    dest: "/srv/minecraft/{{ item.dest }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  loop:
    - { dest: ".mcrcon.pass", content: "{{ mcrcon_pass }}" }
    - { dest: ".world.name", content: "{{ minecraft_world_name }}" }
    - { dest: "ops.json", content: "{{ minecraft_ops }}" }
    - { dest: "whitelist.json", content: "{{ minecraft_allowlist }}" }

- name: Write minecraft properties template file
  no_log: true
  template:
    src: templates/server.properties.j2
    dest: /srv/minecraft/server.properties
