---

roles:
    - name: artis3n.tailscale
    - name: petermosmans.customize-gnome

collections:
    - name: community.general
    - name: community.docker
    - name: drew1kun.fancyfonts
    - name: debops.debops
