---

roles:
    - name: artis3n.tailscale
    - name: petermosmans.customize-gnome
    - name: ctorgalson.nerdfonts

collections:
    - name: community.general
    - name: community.docker
    - name: debops.debops
