- name: Core playbook
  hosts: "*"
  become: yes

  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ username }}/.cargo/bin"

  # ----- ----- ----- ----- -----
  # Task imports
  # ----- ----- ----- ----- -----

  tasks:

    # ----- ----- ----- ----- -----
    # CORE
    # ----- ----- ----- ----- -----

    - include_role:
        name: core

    - include_role:
        name: fs_snapshots

    # ----- ----- ----- ----- -----
    # WORKSTATION
    # ----- ----- ----- ----- -----

    - when: inventory_hostname in groups.workstation
      block:
        - include_role:
            name: workstation

        - include_role:
            name: vscode

        - include_role:
            name: gdrive_obsidian
          vars:
            gdrive_client_id: "{{ secret_gdrive_client_id }}"
            gdrive_client_secret: "{{ secret_gdrive_client_secret }}"
            gdrive_root_folder_id: "{{ secret_gdrive_root_folder_id }}"

    # ----- ----- ----- ----- -----
    # SERVER
    # ----- ----- ----- ----- -----

    - name: Server tasks
      include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.server
      with_fileglob:
        - "tasks/server/**.yaml"
      loop_control:
        loop_var: task_items

    # ----- ----- ----- ----- -----
    # MEDIA
    # ----- ----- ----- ----- -----

    - include_role:
        name: media
      when: inventory_hostname in groups.media

    # ----- ----- ----- ----- -----
    # MINECRAFT
    # ----- ----- ----- ----- -----

    - name: Minecraft role
      include_role:
        name: tquin.minecraft_fabric_server
      when: inventory_hostname in groups.minecraft
      vars:
        mcrcon_pass: "{{ secret_mcrcon_pass }}"
        minecraft_ops: "{{ secret_minecraft_ops }}"
        minecraft_allowlist: "{{ secret_minecraft_allowlist }}"

    # ----- ----- ----- ----- -----
    # BACKUP
    # ----- ----- ----- ----- -----

    - name: Backup role
      include_role:
        name: rclone_backup
      when:
        - inventory_hostname in groups.backup
        ##### ##### ##### ##### #####
        # Temporarily disabling due to:
        # https://github.com/tigattack/ansible-rclone-rc-remotes/issues/1
        - false
        ##### ##### ##### ##### #####
      vars:
        # HTTP server
        rclone_rc_pass: "{{ secret_rclone_rc_pass }}"
        # Google Photos
        rclone_gphotos_token: "{{ secret_rclone_gphotos_token }}"
        # Azure blob
        rclone_azure_account: "{{ secret_rclone_azure_account }}"
        rclone_azure_key: "{{ secret_rclone_azure_key }}"
        rclone_azure_crypt_pass: "{{ secret_rclone_azure_crypt_pass }}"

    # ----- ----- ----- ----- -----
    # WIP TEST
    # ----- ----- ----- ----- -----

      # when: inventory_hostname in groups.test
