- hosts: all
  become: yes

  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ username }}/.cargo/bin"

  # ----- ----- ----- ----- -----
  # Bootstrap tasks
  # ----- ----- ----- ----- -----

  # Anything with an earlier dependency should go here
  pre_tasks:
    - include_tasks: "{{ task_items }}"
      with_fileglob:
        # Required before we can do git actions in dotfiles
        - "tasks/core/setup_ssh.yaml"
      loop_control:
        loop_var: task_items

  # ----- ----- ----- ----- -----
  # Task imports
  # ----- ----- ----- ----- -----

  tasks:

    # ----- ----- ----- ----- -----

    - include_tasks: "{{ task_items }}"
      with_fileglob:
        - "tasks/core/**.yaml"
      loop_control:
        loop_var: task_items

    # ----- ----- ----- ----- -----

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.workstation
      with_fileglob:
        - "tasks/workstation/**.yaml"
      loop_control:
        loop_var: task_items

    - include_role: 
        name: gdrive_obsidian
      when: inventory_hostname in groups.workstation
      vars:
        gdrive_client_id: "{{ secret_gdrive_client_id }}"
        gdrive_client_secret: "{{ secret_gdrive_client_secret }}"
        gdrive_root_folder_id: "{{ secret_gdrive_root_folder_id }}"

    # ----- ----- ----- ----- -----

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.server
      with_fileglob:
        - "tasks/server/**.yaml"
      loop_control:
        loop_var: task_items

    # ----- ----- ----- ----- -----

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.media
      with_fileglob:
        - "tasks/media/**.yaml"
      loop_control:
        loop_var: task_items

    # ----- ----- ----- ----- -----

    - include_role: 
        name: minecraft_server
      when: inventory_hostname in groups.minecraft
      vars:
        mcrcon_pass: "{{ secret_mcrcon_pass }}"
        minecraft_ops: "{{ secret_minecraft_user_json }}"
        minecraft_allowlist: "{{ secret_minecraft_user_json }}"

  # ----- ----- ----- ----- -----
  # Handlers
  # ----- ----- ----- ----- -----

  handlers:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "handlers/**.yaml"
        - "handlers/**.yml"
