prod:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:

# ----- ----- ----- ----- -----

test:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:
    ansiblevm-ubuntu22:
      ansible_host: 192.168.122.194
    ansiblevm-debian12:
      ansible_host: 192.168.122.7
    ansiblevm-fedora39:
      ansible_host: 192.168.122.21
