prod:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:
    MANCHESTER-BABY:
      ansible_host: 100.68.26.36

# ----- ----- ----- ----- -----

test:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:
    ansiblevm-ubuntu22:
      ansible_host: 192.168.124.232
    ansiblevm-debian12:
      ansible_host: 192.168.124.80
    ansiblevm-fedora39:
      ansible_host: 192.168.124.23
