- name: Check if cargo is installed
  command: which cargo
  register: cargo_exists
  ignore_errors: yes
  changed_when: no

# ----- ----- ----- ----- -----

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'

- name: Install rust, cargo toolset
  become_user: "{{ username }}"
  when: cargo_exists is failed
  shell: |
    /tmp/sh.rustup.rs -y
    rustup default stable
  changed_when: yes

- name: Cleanup installer
  when: cargo_exists is failed
  file:
    path: /tmp/sh.rustup.rs
    state: absent

# ----- ----- ----- ----- -----

- name: Update rust, cargo toolset
  become_user: "{{ username }}"
  when: cargo_exists is succeeded
  shell: |
    rustup update
  changed_when: yes

# ----- ----- ----- ----- -----

- name: Install cargo/rust packages
  become_user: "{{ username }}"
  community.general.cargo:
    name: "{{ item }}"
    locked: yes
  loop: "{{ cargo_packages }}"

# User's cargo path will be added by dotfiles.yaml
