- name: Install and start cf-ddns through Docker
  community.docker.docker_container:
    name: cf-ddns
    image: favonia/cloudflare-ddns
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    capabilities:
      - SETUID
      - SETGID
    network_mode: host
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGUID: "{{ username_guid }}"
      PGID: "{{ username_guid }}"
      PROXIED: "true"
      CF_API_TOKEN: "{{ cf_ddns_token }}"
      DOMAINS: "{{ cf_ddns_domains | join(',') }}"
