# ----- ----- ----- ----- -----
# Shared variables across all hosts
# ----- ----- ----- ----- -----

username: till
time_zone: Australia/Victoria
docker_container_dir: "/docker"

# ----- ----- ----- ----- -----

dotfiles_repo: https://github.com/tquin/dotfiles
dotfiles_dir: "/home/{{ username }}/code/dotfiles"

# ----- ----- ----- ----- -----

common_packages:
  - zsh
  - nano
  - vim
  - micro
  - git
  - tmux # needed for alacritty config
  - htop
  - btop # fancy htop
  - bat # fancy cat
  - speedtest-cli
  - stow
  - neofetch
  - tlp # CPU / power profiles
  - powertop
  - virt-manager

  # Requirements for rust_cargo.yaml
  - cmake
  - make
  - gcc
  - curl

ubuntu_packages:
  - 7zip
  - exa # fancy ls (old)

debian_packages:
  # Requirements for setup_docker.yaml
  - apt-transport-https
  - ca-certificates
  - wget
  - software-properties-common
  - gnupg2
  - exa # fancy ls (old)

fedora_packages:
  - eza # fancy ls (new)
  - btrfs-assistant
  # Requirements for setup_docker.yaml
  - dnf-plugins-core

# ----- ----- ----- ----- -----

cargo_packages:
  - starship
  - du-dust
  - bacon
  - ripgrep
  - gping

cargo_dir: "/home/{{ username }}/.cargo/bin"
