# ----- ----- ----- ----- -----
# Shared variables across all hosts
# ----- ----- ----- ----- -----

username: till
time_zone: Australia/Victoria

# ----- ----- ----- ----- -----

dotfiles_repo: https://github.com/tquin/dotfiles
dotfiles_dir: "/home/{{ username }}/code/dotfiles"

# ----- ----- ----- ----- -----

common_packages:
  - zsh
  - nano
  - vim
  - micro
  - git
  - tmux # needed for alacritty config
  - htop
  - btop # fancy htop
  - bat # fancy cat
  - exa # fancy ls
  - speedtest-cli
  - stow
  - neofetch
  - tlp # CPU / power profiles
  # Requirements for rust_cargo.yaml
  - cmake
  - make
  - gcc
  - curl

ubuntu_packages:
  - 7zip

debian_packages:
  # Requirements for setup_docker.yaml
  - apt-transport-https
  - ca-certificates
  - wget
  - software-properties-common
  - gnupg2

fedora_packages:
  # Requirements for setup_docker.yaml
  - dnf-plugins-core

# ----- ----- ----- ----- -----

cargo_packages:
  - starship
  - du-dust
  - bacon
  - ripgrep
  - gping

cargo_dir: "/home/{{ username }}/.cargo/bin"
