- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/grafana/data"

# Problems running as user, needs to be root
- name: Install and start Grafana through Docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana-oss
    user: "0"
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "bridge"
    ports:
      - "3000:3000"
    env:
      TZ: "{{ time_zone }}"
      GF_INSTALL_PLUGINS: "{{ grafana_plugins | join(',') }}"
    volumes:
      - "{{ docker_container_dir }}/grafana/data:/var/lib/grafana"
