- name: Create minecraft user account
  user:
    name: "{{ minecraft_user }}"

- name: Copy minecraft scripts and config files
  copy: 
    src: ../resources/minecraft/srv/
    dest: /srv/minecraft/
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Create minecraft backups directory
  file:
    path: /srv/minecraft/backups/
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Add minecraft script x permissions
  file:
    path: /srv/minecraft/{{ item }}
    mode: a+x
  loop:
    - start.sh
    - stop.sh
    - backup.sh

- name: Write minecraft variables to files
  no_log: true
  copy:
    content: "{{ item.content }}"
    dest: "/srv/minecraft/{{ item.dest }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  with_items:
    - { dest: ".mcrcon.pass", content: "{{ secret_mcrcon_pass }}" }
    - { dest: ".world.name", content: "{{ minecraft_world_name }}" }
    - { dest: "ops.json", content: "{{ secret_minecraft_ops }}" }
    - { dest: "whitelist.json", content: "{{ secret_minecraft_allowlist }}" }

- name: Write variables in minecraft properties file
  no_log: true
  lineinfile:
    path: /srv/minecraft/server.properties
    regexp: "^{{ item.property_name }}"
    line: "{{ item.property_name }}={{ item.property_value }}"
  with_items:
    - { property_name: "level-seed", property_value: "{{ minecraft_world_name }}" }
    - { property_name: "motd", property_value: "{{ minecraft_motd }}" }
    - { property_name: "level-seed", property_value: "{{ minecraft_seed }}" }
    - { property_name: "rcon.password", property_value: "{{ secret_mcrcon_pass }}" }
