- name: Create minecraft user account
  user:
    name: "{{ minecraft_user }}"

# ----- ----- ----- ----- -----

- set_fact:
    java_package: >-
      {% if ansible_distribution == 'Fedora' %}
      java-17-openjdk
      {% elif (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian') %}
      openjdk-17-jre-headless
      {% endif %}

- name: Install Java environment
  package:
    name: "{{ java_package | regex_replace('\\s', '') }}"
    state: latest

# ----- ----- ----- ----- -----

- name: Create minecraft server jar directory
  file:
    path: /srv/minecraft/jar_versions/
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Download latest Fabric JAR
  args:
    chdir: /srv/minecraft/jar_versions/
  shell: |
    wget -O "fabric-{{ minecraft_version }}.jar" "https://meta.fabricmc.net/v2/versions/loader/{{ minecraft_version }}/{{ minecraft_fabric_version }}/server/jar"

- name: Create symlink to minecraft server.jar
  become_user: "{{ minecraft_user }}"
  file:
    src: "/srv/minecraft/jar_versions/fabric-{{ minecraft_version }}.jar"
    dest: /srv/minecraft/server.jar
    state: link
