- name: Copy minecraft service files
  copy: 
    src: "resources/minecraft/systemd/"
    dest: "/etc/systemd/system"

- name: Enable and start minecraft service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: minecraft.service

- name: Enable minecraft backup service and timer
  systemd:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
  loop:
    - minecraft-backup.service
    - minecraft-backup.timer
