- name: Update packages
  apt: 
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name: "{{ common_packages }}"
    state: latest

- name: Install Ubuntu-only packages
  when: ansible_distribution == 'Ubuntu'
  package:
    name: "{{ ubuntu_packages }}"
    state: latest

- name: Install Debian-only packages
  when: ansible_distribution == 'Debian'
  package:
    name: "{{ debian_packages }}"
    state: latest
