- name: Update packages
  apt: 
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name: "{{ common_packages }}"
    state: latest

- name: Install Ubuntu-only packages
  package:
    name: "{{ ubuntu_packages }}"
    state: latest
  when: ansible_distribution == 'Ubuntu'
