- name: Update apt packages
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    upgrade: yes

- name: Update dnf packages
  when: ansible_os_family == 'RedHat'
  dnf:
    name: "*"
    state: latest

# ----- ----- ----- ----- -----

- name: Install essential packages
  package:
    name: "{{ common_packages }}"
    state: latest

- name: Install Ubuntu-only packages
  when: ansible_distribution == 'Ubuntu'
  package:
    name: "{{ ubuntu_packages }}"
    state: latest

- name: Install Debian-only packages
  when: ansible_distribution == 'Debian'
  package:
    name: "{{ debian_packages }}"
    state: latest

- name: Install Fedora-only packages
  when: ansible_distribution == 'Fedora'
  package:
    name: "{{ fedora_packages }}"
    state: latest

# ----- ----- ----- ----- -----

- name: Autoremove apt packages
  when: ansible_os_family == 'Debian'
  apt:
    autoremove: true

- name: Autoremove dnf packages
  when: ansible_os_family == 'RedHat'
  dnf:
    autoremove: yes
