- name: Chown the repo
  file:
    path: "{{ dotfiles_dir }}"
    recurse: yes
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Clone the latest dotfiles repo
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    clone: yes
    recursive: yes
    track_submodules: yes
    force: yes
    accept_newhostkey: yes

- name: Stow the dotfiles
  become_user: "{{ username }}"
  command:
    cmd: "stow -v --target=/home/{{ username }} ."
    chdir: "{{ dotfiles_dir }}"
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Add shell sourcing
  lineinfile:
    name: "{{ item }}"
    line: "source {{ dotfiles_dir }}/bashrc.till"
    state: present
  loop:
    - "/home/{{ username }}/.bashrc"
    - "/home/{{ username }}/.zshrc"
