# Debian Bullseye ships an ancient version of Cargo,
# so we need to manaully update it outside apt.
- name: Check if cargo is outdated from Debian
  when: ansible_distribution == 'Debian'
  shell: |
    rustup default stable
    cargo --version | grep 'cargo 1.4'
  register: cargo_deb_outdated
  ignore_errors: yes

- name: Remove apt version of cargo from Debian (apt-remove)
  when: ansible_distribution == 'Debian' and cargo_deb_outdated is defined
  package:
    name: "{{ remove_pkg_item }}"
    state: absent
  loop:
    - cargo
    - rustc
  loop_control:
    loop_var: remove_pkg_item

- name: Remove apt version of cargo from Debian (apt-autoremove)
  when: ansible_distribution == 'Debian' and cargo_deb_outdated is defined
  apt:
    autoremove: true

# ----- ----- ----- ----- -----

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'

- name: Install rust, cargo toolset
  become_user: "{{ username }}"
  when: cargo_exists is failed
  shell: |
    /tmp/sh.rustup.rs -y
    rustup default stable

- name: Install cargo/rust packages
  become_user: "{{ username }}"
  community.general.cargo:
    name: "{{ cargo_item }}"
  loop: "{{ cargo_packages }}"
  loop_control:
    loop_var: cargo_item

# User's cargo path will be added by dotfiles.yaml

- name: Cleanup installer
  file:
    path: /tmp/sh.rustup.rs
    state: absent
