- name: Add Apt signing key from official docker repo
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ os_version }} stable"
    state: present

- name: Install Docker packages
  apt:
    name: "{{  docker_package }}"
    state: latest
  loop:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin
  loop_control:
    loop_var: docker_package
