- name: Add Apt signing key from official docker repo
  when: (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian')
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker apt repository
  when: (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian')
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Add Docker dnf repository
  when: ansible_distribution == 'Fedora'
  yum_repository:
    name: docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Enable and start Docker service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: docker.service
