- name: "Get UID and GUID of {{ username }}"
  getent:
    database: passwd
    key: "{{ username }}"

- name: Set UID/GUID variables
  set_fact:
    username_uid: "{{ getent_passwd[item].1 }}"
    username_guid: "{{ getent_passwd[item].2 }}"
  loop:
    - "{{ username }}"
