cf_zone: "example.com"
cf_ddns_domains:
  - apple.example.com
  - banana.example.com

ts_domain: "{{ inventory_hostname }}.{{ secret_tailscale_domain }}.ts.net"
ts_serve_internal_port: "5055" # Overseer

# src must be under cf_zone
cf_dns_forwards:
  - type: CNAME
    src: cantalope.example.com
    dest: "{{ ts_domain }}"
