# ----- ----- ----- ----- -----
# caddy
# ----- ----- ----- ----- -----

caddy_version: "2.8"
# Used for certs
caddy_email: "" # Fill from vault
caddy_domain: "example.com"
cf_dns_token: "" # Fill from vault

caddy_subdomain_mapping:
  - { name: homer, port: 8080}

# ----- ----- ----- ----- -----
# ddns
# ----- ----- ----- ----- -----

cf_ddns_domains:
  - apple.example.com
  - banana.example.com
