# This could vary across OSes so no hardcoding
- name: Get reboot binary absolute path
  command: which reboot
  register: reboot_info
  ignore_errors: true
  changed_when: false

- name: Add scheduled reboot entry to cron
  cron:
    name: "Scheduled automatic reboots"
    job: "{{ reboot_info.stdout }}"
    minute: "{{ reboot_cron_min }}"
    hour: "{{ reboot_cron_hour }}"
    weekday: "{{ reboot_cron_weekday }}"
