# https://docs.debops.org/en/master/ansible/roles/unattended_upgrades/
- name: Enable unattended upgrades (Debian)
  when: ansible_os_family == 'Debian'
  include_role:
    name: debops.debops.unattended_upgrades

# https://galaxy.ansible.com/exploide/dnf-automatic
- name: Enable unattended upgrades (RedHat)
  when: ansible_os_family == 'RedHat'
  include_role:
    name: exploide.dnf-automatic
