# ----- ----- ----- ----- -----
# Copy files to remote
# ----- ----- ----- ----- -----

- name: Create Wireguard directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/wireguard/config"
    - "{{ docker_container_dir }}/common/"

- name: Copy wireguard .conf file
  template:
    src: "{{ wireguard_conf_file }}"
    dest: "{{ docker_container_dir }}/wireguard/config/wg0.conf"
    mode: '660'

- name: Copy startup script for other containers
  template:
    src: "vpn_routes_startup.sh.j2"
    dest: "{{ docker_container_dir }}/common/vpn_routes_startup.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '660'

# ----- ----- ----- ----- -----
# Host kernel modules
# ----- ----- ----- ----- -----

- name: Wireguard package name (Debian)
  when: ansible_os_family == 'Debian'
  set_fact:
    wireguard_package: wireguard

- name: Wireguard package name (RedHat)
  when: ansible_os_family == 'RedHat'
  set_fact:
    wireguard_package: wireguard-tools

- name: Install wireguard package
  package:
    name: "{{ wireguard_package }}"

- name: Load the wireguard kernel module
  community.general.modprobe:
    name: wireguard
    state: present
    persistent: present

# ----- ----- ----- ----- -----
# Create network & container
# ----- ----- ----- ----- -----

- name: Create wireguard docker network
  community.docker.docker_network:
    name: "{{ wireguard_network_name }}"
    ipam_config:
      - subnet: "{{ wireguard_subnet }}"
        gateway: "{{ wireguard_default_gateway }}"

- name: Install and start wireguard through Docker
  community.docker.docker_container:
    name: wireguard
    image: linuxserver/wireguard
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    privileged: true
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - "{{ docker_container_dir }}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGUID: "{{ username_guid }}"
    networks:
      - name: "{{ wireguard_network_name }}"
        ipv4_address: "{{ wireguard_static_ip }}"
