# https://docs.debops.org/en/master/ansible/roles/unattended_upgrades/
- name: Enable unattended upgrades
  when: (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian')
  include_role:
    name: debops.debops.unattended_upgrades