- name: Create Overseerr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/overseerr/config"
    - "{{ media_container_root_dir }}"

- name: Install and start Overseerr through Docker
  community.docker.docker_container:
    name: overseerr
    hostname: overseerr
    image: sctx/overseerr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['overseerr'] }}"
    dns_servers:
      - "{{ docker_dns_server }}"
    ports:
      - "5055:5055"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
      PORT: "5055"
    volumes:
      - "{{ docker_container_dir }}/overseerr/config:/app/config"
      - "{{ docker_container_dir }}/common:/common"
    command: >-
      {{
        "bash /common/vpn_routes_startup.sh"
        if ( media_network_modes['overseerr'] == wireguard_network_name )
        else ""
      }}
