- name: Create Plex directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/plex/config"
    - "{{ docker_container_dir }}/plex/transcode"
    - "{{ media_container_root_dir }}"

- name: Install and start Plex through Docker
  community.docker.docker_container:
    name: plex
    image: plexinc/pms-docker
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['plex'] }}"
    capabilities:
      - NET_ADMIN
    # Ports not needed in Host network mode
    # ports:
    #  - "32400:32400/tcp"
    env:
      TZ: "{{ time_zone }}"
      PLEX_UID: "{{ username_uid }}"
      PLEX_GID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/plex/config:/config"
      - "{{ docker_container_dir }}/plex/transcode:/transcode"
      - "{{ media_container_root_dir }}:/data"
      - "{{ docker_container_dir }}/common:/common"
    command: >-
      {{
        "bash /common/vpn_routes_startup.sh"
        if ( media_network_modes['plex'] == wireguard_network_name )
        else ""
      }}
