- name: Create podqueue directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/podqueue/config"
    - "{{ media_data_dir }}/podcasts"

- name: Copy podqueue.opml file
  become_user: "{{ username }}"
  copy:
    src: "resources/media/{{ podqueue_opml_file_name }}"
    dest: "{{ media_data_dir }}/podcasts/podqueue.opml"
    owner: "{{ username }}"
    group: "{{ username }}"
    # Note: this has to be a string, not an int!!
    mode: '660'

- name: Install and start podqueue through Docker
  community.docker.docker_container:
    name: podqueue
    image: tquin/podqueue
    state: started
    user: "{{ username_uid }}:{{ username_guid }}"
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['podqueue'] }}"
    volumes:
      - "{{ media_data_dir }}/podcasts:/data"
      - "{{ docker_container_dir }}/podqueue/config:/config"
