- name: Create Sonarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/sonarr/config"
    - "{{ media_container_root_dir }}"

- name: Install and start Sonarr through Docker
  community.docker.docker_container:
    name: sonarr
    hostname: sonarr
    image: hotio/sonarr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['sonarr'] }}"
    dns_servers: 
      - "{{ docker_dns_server }}"
    ports:
      - "8989:8989"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/sonarr/config:/config"
      - "{{ media_container_root_dir }}:/data"
      - "{{ docker_container_dir }}/common:/common"
    command: >-
      {{
        "bash /common/vpn_routes_startup.sh"
        if ( media_network_modes['sonarr'] == wireguard_network_name )
        else ""
      }}
