- name: Create Transmission directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/transmission/config"
    - "{{ media_container_root_dir }}"

- name: Install and start Transmission through Docker
  community.docker.docker_container:
    name: transmission
    image: linuxserver/transmission
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['transmission'] }}"
    dns_servers: 
      - "{{ docker_dns_server }}"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/transmission/config:/config"
      - "{{ media_container_root_dir }}/torrents:/downloads"
      - "{{ docker_container_dir }}/common:/common"
    command: >-
      {{
        "bash /common/vpn_routes_startup.sh"
        if ( media_network_modes['transmission'] == wireguard_network_name )
        else ""
      }}
