- name: Check if alacritty is installed
  command: which alacritty
  register: alacritty_exists
  ignore_errors: yes
  changed_when: no

- name: Install/Update alacritty through Docker build environment
  community.docker.docker_container:
    name: build-alacritty
    image: bstlang/build-alacritty
    state: started
    volumes:
      - /usr/local:/out
    env:
      VERSION: "{{ alacritty_version }}"
    cleanup: true

- name: Download alacritty extras from GitHub
  when: alacritty_exists is failed
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '664'
  loop:
    - url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/linux/Alacritty.desktop
      dest: /tmp/Alacritty.desktop
    - url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/logo/alacritty-term.svg
      dest: /usr/share/pixmaps/Alacritty.svg

- name: Add alacritty to application list
  when: alacritty_exists is failed
  command: desktop-file-install /tmp/Alacritty.desktop
  changed_when: true
