- name: Install apt GPG key for Sublime Text
  when: (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian')
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Install rpm GPG key for Sublime Text
  when: ansible_distribution == 'Fedora'
  rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

# ----- ----- ----- ----- -----

- name: Add Sublime Text repo to apt
  when: (ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian')
  apt_repository:
    repo: deb https://download.sublimetext.com apt/stable/
    filename: sublime
    state: present
    update_cache: true

- name: Add Sublime Text repo to dnf
  when: ansible_distribution == 'Fedora'
  get_url:
    url: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    dest: /etc/yum.repos.d

# ----- ----- ----- ----- -----

- name: Install Sublime Text
  package:
    name: sublime-text
    state: latest
