- name: Create Bazarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - "{{ docker_container_dir }}/bazarr/config"
    - "{{ media_data_dir }}/media"

- name: Install and start Bazarr through Docker
  community.docker.docker_container:
    name: bazarr
    image: hotio/bazarr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ media_network_modes['bazarr'] }}"
    ports:
      - "6767:6767"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/bazarr/config:/config"
      - "{{ media_data_dir }}/media:/data/media"
