- name: Create podqueue directory
  file:
    path: "{{ podqueue_output_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy podqueue.opml file
  become_user: "{{ username }}"
  copy: 
    src: "../resources/media/{{ podqueue_opml_file_name }}"
    dest: "{{ podqueue_output_dir }}/podqueue.opml"
    owner: "{{ username }}"
    group: "{{ username }}"
    # Note: this has to be a string, not an int!!
    mode: '660'

- name: Install and start podqueue through Docker
  community.docker.docker_container:
    name: podqueue
    image: tquin/podqueue:main
    state: started
    user: "{{ username_uid }}:{{ username_guid }}"
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    volumes:
      - "{{ podqueue_output_dir }}:/pq"
    network_mode: "{{ wireguard_network_name }}"
