- hosts: all
  become: yes

  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ username }}/.cargo/bin"

  # ----- ----- ----- ----- -----
  # Bootstrap tasks
  # ----- ----- ----- ----- -----

  # Anything with an earlier dependency should go here
  pre_tasks:
    - include_tasks: "{{ task_items }}"
      with_fileglob:
        # Required before we can do git actions in dotfiles
        - "../tasks/core/setup_ssh.yaml"
      loop_control:
        loop_var: task_items

  # ----- ----- ----- ----- -----
  # Task imports
  # ----- ----- ----- ----- -----

  tasks:
    - include_tasks: "{{ task_items }}"
      with_fileglob:
        - "../tasks/core/**.yaml"
        - "../tasks/core/**.yml"
      loop_control:
        loop_var: task_items

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.workstation
      with_fileglob:
        - "../tasks/workstation/**.yaml"
        - "../tasks/workstation/**.yml"
      loop_control:
        loop_var: task_items

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.server
      with_fileglob:
        - "../tasks/server/**.yaml"
        - "../tasks/server/*.yaml"
      loop_control:
        loop_var: task_items

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.minecraft
      with_fileglob:
        - "../tasks/minecraft/**.yaml"
        - "../tasks/minecraft/*.yaml"
      loop_control:
        loop_var: task_items

  # ----- ----- ----- ----- -----
  # Handlers
  # ----- ----- ----- ----- -----

  handlers:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "../handlers/**.yaml"
        - "../handlers/**.yml"
