- hosts: all
  become: yes

  tasks:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "../tasks/**.yaml"
        - "../tasks/**.yml"

  roles:
    # https://github.com/artis3n/ansible-role-tailscale
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ secret_tailscale_authkey }}"
        tailscale_args: "--ssh"
        state: latest

  handlers:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "../handlers/**.yaml"
        - "../handlers/**.yml"