- hosts: all
  become: yes

  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ username }}/.cargo/bin"

  # ----- ----- ----- ----- -----
  # Handlers
  # ----- ----- ----- ----- -----

  handlers:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "../handlers/**.yaml"
        - "../handlers/**.yml"


  # ----- ----- ----- ----- -----
  # Local tasks
  # ----- ----- ----- ----- -----

  # Anything with an earlier dependency should go here
  pre_tasks:
    - include_tasks: "{{ task_items }}"
      with_fileglob:
        # Required before we can do git actions in dotfiles
        - "../tasks/core/setup_ssh.yaml"
      loop_control:
        loop_var: task_items

  tasks:
    - include_tasks: "{{ task_items }}"
      with_fileglob:
        - "../tasks/core/**.yaml"
        - "../tasks/core/**.yml"
      loop_control:
        loop_var: task_items

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.workstation
      with_fileglob:
        - "../tasks/workstation_apps/**.yaml"
        - "../tasks/workstation_apps/**.yml"
      loop_control:
        loop_var: task_items

    - include_tasks: "{{ task_items }}"
      when: inventory_hostname in groups.minecraft
      with_fileglob:
        - "../tasks/minecraft/**.yaml"
        - "../tasks/minecraft/*.yaml"
      loop_control:
        loop_var: task_items

    # ----- ----- ----- ----- -----
    # Galaxy tasks/PBs
    # ----- ----- ----- ----- -----

    # https://github.com/artis3n/ansible-role-tailscale
    - name: Install tailscale
      include_role: 
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ secret_tailscale_authkey }}"
        tailscale_args: "--ssh"
        state: latest

    # https://github.com/drew1kun/ansible-collection-fancyfonts
    - name: Install Nerdfonts
      include_role:
        name: "{{ nerdfont_item }}"
      loop:
        - drew1kun.fancyfonts.nerdfonts
        - drew1kun.fancyfonts.terminus_powerline
      loop_control:
        loop_var: nerdfont_item

    # https://docs.debops.org/en/master/ansible/roles/fail2ban/
    - name: Install fail2ban
      when: inventory_hostname in groups.server
      include_role:
        name: debops.debops.fail2ban

    # TBD - BROKEN BY DIG/DNSPYTHON ISSUE
    # https://docs.debops.org/en/master/ansible/roles/nullmailer/
    #- name: Install nullmailer forwarder
    #  when: inventory_hostname in groups.server
    #  include_role:
    #    name: debops.debops.nullmailer

    # https://docs.debops.org/en/master/ansible/roles/unattended_upgrades/
    - name: Enable unattended upgrades
      when: inventory_hostname in groups.server
      include_role:
        name: debops.debops.unattended_upgrades
