minecraft_user: "minecraft"

minecraft_version: "1.20"
minecraft_fabric_version: "0.14.21/0.11.2" # Loader / Installer

minecraft_world_name: "my_minecraft_world"
minecraft_seed: "8624896"
minecraft_motd: "A Minecraft Server"

# This should be the 'slug' from the URL, eg: modrinth.com/mods/<slug>
minecraft_mods:
  - fabric-api
  - sodium
  - lithium
  - fabric-language-kotlin
  - indium

# Should be passed in to the role from a vault
mcrcon_pass: ""
minecraft_ops: ""
minecraft_allowlist: ""
