# btrfs
- name: Check if btrfs is installed
  lineinfile:
    path: /proc/filesystems
    regexp: '\sbtrfs$'
    state: absent
  check_mode: yes
  changed_when: false
  register: btrfs_check

- include_tasks: btrfs_snaps.yaml
  when: btrfs_check.found

# ZFS
- name: Check if zfs is installed
  lineinfile:
    path: /proc/filesystems
    regexp: '\szfs$'
    state: absent
  check_mode: yes
  changed_when: false
  register: zfs_check

- include_tasks: zfs_snaps.yaml
  when: zfs_check.found
